language: vim

before_script: |
  git clone https://github.com/junegunn/vader.vim.git --depth 1
  git clone https://github.com/tpope/vim-repeat.git --depth 1

script: |
  vim -Nu <(cat << VIMRC
  filetype off
  set rtp+=vader.vim
  set rtp+=vim-repeat
  set rtp+=.
  set rtp+=after
  filetype plugin indent on
  syntax enable
  VIMRC) -c 'Vader! test/spaced.vader' > /dev/null
